{block #componentRender}

	<li  {if ($object instanceof \Nette\Application\Presenter) && (!$object instanceOf \Nette\Forms\FormControl)}class="open"{/if}>

		{var $refl => $object->getReflection()}

		<b>{$object->name}</b>
		<i>instance of</i> {=get_class($object)}
		<i>extends</i> {$refl->getParentClass()->getName()}

		<a class='phpdoc' title="{$refl->getFileName()}" href="{!=\Extras\Debug\ComponentTreePanel::createEditLink($refl->getFileName(), $refl->getStartLine())}">edit</a>

		<?php

			$cache = \Nette\Environment::getCache('Debug.Panels.ComponentTree');
				$cached = $cache[$object->name];
				echo $cached;
			}
			else {
				ob_start();
		?>
		<a class="nette-toggler" href="#"><abbr>&#x25ba;</abbr></a>
		<ul class="nette-hidden">
			<li>

				<i>Methods</i><a class="nette-toggler" href="#"><abbr>&#x25ba;</abbr></a>

				<ul class="nette-hidden">

					<!-- aciton<action>, beforeRender<view>-->

					{if $object instanceof \Nette\Application\Presenter}
						{include
							methods.phtml
							name => "action<Action>", object => $object, inherited => TRUE, pattern => "#^(action)(.+)#"}
						{include
							methods.phtml
							name => "lifecycle", object => $object, inherited => TRUE, pattern => "~\A()(startup | beforeHandle | beforeRender |shutdown)\z~x"}
					{/if}

					<!-- render<view>, handle<signal> -->

					{if $object instanceof \Nette\Application\Control}
						{include methods.phtml
							name => "render<View>", object => $object, inherited => TRUE, pattern => "#^(render)(.*)#"}
						{include methods.phtml
							name => "handle<Signal>", object => $object, inherited => TRUE, pattern => "#^(handle)(.*)#", hideMethods => array()}
					{/if}

					<!-- createComponent -->

					{include methods.phtml name => "createComponent<name>", object => $object, inherited => TRUE, pattern => "#^(createComponent)(.+)#", hideMethods => array()}

					<!-- create<object>-->
					{include methods.phtml name => "create<object>", object =>$object, inherited => TRUE, pattern => "#^(create(?!Component))(\w+)#", hideMethods => array('createRequest')}

					<!-- get/set properties-->

					{include methods.phtml
						name => "get<property>", object => $object, inherited => FALSE, pattern => "#^(get)(.+)#"}

					{include methods.phtml
						name => "set<property>", object => $object, inherited => FALSE, pattern => "#^(set)(.*)#"}
				</ul>
			{if !$object instanceOf \Nette\Application\AppForm}
			<li><i>Source File</i><a class="nette-toggler" href="#"><abbr>&#x25ba;</abbr></a>
				<ul class="nette-hidden">
					{include sourcefile.phtml, object => $object, showSource => TRUE}
				</ul>
			{/if}
			<?php
					$content = ob_get_clean();
					echo $content;
					$cache->save($object->name, $content, array('files'=>array($refl->getFileName())));
				}
			?>


	<!--! Childs COMPONENTS -->

	{if $object instanceOf \Nette\ComponentContainer}
		<?php
		$filteredComponents = array();

		foreach ($object->components as $component) {
			if ($component instanceof \Extras\Debug\ComponentTreeControl) {
				continue;
			}
			$filteredComponents[] = $component;
		}
		?>

		<li>
			<i>Child Components ({=count($filteredComponents)})</i><a class="nette-toggler" href="#"><abbr>&#x25ba;</abbr></a>
			<ul n:if="count($filteredComponents)>0" class="nette-hidden">
				{foreach $filteredComponents as $com}
					{include #componentRender object => $com}
				{/foreach}
			</ul>
	{/if}
{/block}