{*
	@param object mixed
	@param opened bool
	@param childOpened bool
	@param cache bool
*}

{block #componentRender}

	<li>

		{var $refl => $object->getReflection()}

		<b>{$object->name}</b>
		<i>instance of</i>
			<a title="{$refl->getFileName()}" href="{!=\Extras\Debug\ComponentTreePanel::createEditLink($refl->getFileName(), $refl->getStartLine())}">
				{=get_class($object)}
			</a>
			{var $parent = $refl->getParentClass()}
			<i>extends</i> <a title="{$parent->getFileName()}" href="{!=\Extras\Debug\ComponentTreePanel::createEditLink($parent->getFileName(), $parent->getStartLine())}">{$parent->getName()}</a>

		<a class="nette-toggler" href="#" rel="next"> <abbr>{if $opened}&#x25bc{else}&#x25ba{/if};</abbr></a>
		<ul {if !$opened}class="nette-hidden"{/if}>

		<?php

			if ($cache && isset($cache[$object->name])) {
				$cached = $cache[$object->name];
				echo $cached;
			}
			else {
				ob_start();
		?>

			<li>
				Methods <a class="nette-toggler" rel="next" href="#"><abbr>&#x25ba;</abbr></a>
				<ul class="nette-hidden">

					<!-- aciton<action>, beforeRender<view>-->

					{if $object instanceof \Nette\Application\IPresenter}
						{include
							methods.phtml
							name => "action<Action>", object => $object, inherited => TRUE, pattern => "#^(action)(.+)#"}
						{include
							methods.phtml
							name => "lifecycle", object => $object, inherited => TRUE, pattern => "~\A()(startup | beforeHandle | beforeRender |shutdown)\z~x"}
					{/if}

					<!-- render<view>, handle<signal> -->

					{if $object instanceof \Nette\Application\Control}
						{include methods.phtml
							name => "render<View>", object => $object, inherited => TRUE, pattern => "#^(render)(.*)#"}
						{include methods.phtml
							name => "handle<Signal>", object => $object, inherited => TRUE, pattern => "#^(handle)(.*)#", hideMethods => array()}
					{/if}

					<!-- createComponent -->

					{include methods.phtml name => "createComponent<name>", object => $object, inherited => TRUE, pattern => "#^(createComponent)(.+)#", hideMethods => array()}

					<!-- create<object>-->
					{include methods.phtml name => "create<object>", object =>$object, inherited => TRUE, pattern => "#^(create(?!Component))(\w+)#", hideMethods => array('createRequest')}

					<!-- get/set properties-->

					{include methods.phtml
						name => "get<property>", object => $object, inherited => FALSE, pattern => "#^(get)(.+)#"}

					{include methods.phtml
						name => "set<property>", object => $object, inherited => FALSE, pattern => "#^(set)(.*)#"}
				</ul>
			{if !$object instanceOf \Nette\Application\UI\Form}
				<li>

					Source File <a class="nette-toggler" rel="next" href="#"><abbr>&#x25ba;</abbr></a>
					<ul class="nette-hidden">
						{include sourcefile.phtml, object => $object, showSource => TRUE}
					</ul>
			{/if}
			<?php
					$content = ob_get_clean();
					echo $content;
					if ($cache) {
						$cache->save($object->name, $content, array('files'=>array($refl->getFileName())));
					}
				}
			?>

	{* Dumps *}

	{if $dumps}
		<li>Dump <a class="nette-toggler" href="#" rel="next"> <abbr>&#x25ba;</abbr></a>
		<ul class="nette-hidden">
			<div class="ct-dump">{!= \Nette\Diagnostics\Helpers::clickableDump($object)}</div>
		</ul>
	{/if}




	{* Components *}

	{if $object instanceOf \Nette\ComponentModel\Container}
		{var $components = $object->getComponents()}
		{if count($components) > 0}
		<li>
			Components ({=count($components)}) <a class="nette-toggler" rel="next" href="#"><abbr>&#x25bc;</abbr></a>
			<ul>
				{foreach $components as $com}
					{include #componentRender object=>$com, opened=>$childOpened, childOpened=>$childOpened}
				{/foreach}
			</ul>
		{/if}
	{/if}
	</ul>

{/block}