<?php
/**
* @param $rootComponent
* @param $BaseUri
* @param $presenter
* @param $template
* @todo Javascript collapsable
* @todo Odkazy na editaci souboru
* @todo TODOS a zobrazovat brat ze souboru
* @todo Refactor: přénést PHP z šablon @component.phtml a @methods.phtml do helperů
*/
?>
<style n:syntax="off">


	#componentsTreeComponent ul,
	#componentsTreeComponent li,
	#componentsTreeComponent ol
	{
		font-family: arial;
		line-height: 1.2;
		font-size:13px;
		list-style: none;
		margin-top: 0;
		margin-bottom: 0;
		margin-left:0em;
		text-align: left;
	}

	#componentsTreeComponent i {
		color:#666;
	}

	#componentsTreeComponent b {
		color:darkgreen;
	}

	#componentsTreeComponent strong {
		color:darkred;
	}

	#componentsTreeComponent code {
		font-family: consolas;
		background:#ddd;
	}

	#componentsTreeComponent .source {
		font-family: consolas;
		background:#ddd;
	}

	#componentsTreeComponent ul {
		list-style-type: none;
		margin-left:10px;
		padding-left:4px;
		background: url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAAKAQMAAABPHKYJAAAAA1BMVEWIiIhYZW6zAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH1ggGExMZBky19AAAAAtJREFUCNdjYMAEAAAUAAHlhrBKAAAAAElFTkSuQmCC') repeat-y;
	}

	#componentsTreeComponent li {
		list-style-type: none;
		padding-left:10px;
		margin-left:-4px;
		background: url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAUAQMAAACK1e4oAAAABlBMVEUAAwCIiIgd2JB2AAAAAXRSTlMAQObYZgAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB9YIBhQIJYVaFGwAAAARSURBVAjXY2hgQIf/GTDFGgDSkwqATqpCHAAAAABJRU5ErkJggg==') no-repeat;
	}

	#componentsTreeComponent li:last-child {
		list-style-type: none;
		padding-left:10px;
		margin-left:-4px;
		background: #fff url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAUAQMAAACK1e4oAAAABlBMVEUAAwCIiIgd2JB2AAAAAXRSTlMAQObYZgAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB9YIBhQIIhs+gc8AAAAQSURBVAjXY2hgQIf/GbAAAKCTBYBUjWvCAAAAAElFTkSuQmCC') no-repeat;

	}




</style>

<script n:syntax="off">
</script>

<h1>Component Tree</h1>

<div class="nette-inner">
	<div id="componentsTreeComponent" style="border:1px solid #aaa;">
		<ul id="tree">
			{include component.phtml, object => $rootComponent, opened=>true}
		</ul>
	</div>
</div>